[package]
name = "radioscope"
version = "0.1.1"
edition = "2024"

[dependencies]
anyhow = "1"
axum = { version = "0.8.8", features = ["ws"] }
cpal = "0.17.0"
dioxus = { version = "0.7", features = ["ssr"] }
dioxus-ssr = "0.7"
lazy_static = "1"
pcap = "2.4.0"
rand = "0.9.2"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0.148"
tokio = { version = "1.49.0", features = ["macros", "rt-multi-thread", "signal", "process"] }
tower-http = { version = "0.6.8", features = ["trace"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }
sqlx = { version = "0.7", default-features = false, features = ["runtime-tokio-rustls", "sqlite", "macros", "chrono"] }
